export const ff = 
({
string_toString: String.prototype.toString,
string_charAt: String.prototype.charAt,
string_charCodeAt: String.prototype.charCodeAt,
string_concat: String.prototype.concat,
string_indexOf: String.prototype.indexOf,
string_lastIndexOf: String.prototype.lastIndexOf,
string_localeCompare: String.prototype.localeCompare,
string_match: String.prototype.match,
string_replace: String.prototype.replace,
string_replace: String.prototype.replace,
string_search: String.prototype.search,
string_slice: String.prototype.slice,
string_split: String.prototype.split,
string_substring: String.prototype.substring,
string_toLowerCase: String.prototype.toLowerCase,
string_toLocaleLowerCase: String.prototype.toLocaleLowerCase,
string_toUpperCase: String.prototype.toUpperCase,
string_toLocaleUpperCase: String.prototype.toLocaleUpperCase,
string_trim: String.prototype.trim,
string_substr: String.prototype.substr,
string_valueOf: String.prototype.valueOf,
string_localeCompare: String.prototype.localeCompare,
})